### ISSUE TITLE
No offset found for Asia/Chongqing timezone

### ISSUE THREAD

**Issue by xlegs** [SpiritIT/timezonecomplete#23]
Error: No offset found.
     at TzDatabase.dstOffsetForRule (http://localhost:8079/assets/js/app.js:7423:19)
    at TzDatabase.totalOffset (http://localhost:8079/assets/js/app.js:7283:34)
    at TimeZone.offsetForUtc (http://localhost:8079/assets/js/app.js:6038:50)
    at DateTime._utcDateToZoneDate (http://localhost:8079/assets/js/app.js:3427:37)
    at DateTime.toZone (http://localhost:8079/assets/js/app.js:3083:24)

Possible relation to closed issue #22.

Code is 
```
deptTime.toZone(timezonecomplete.zone('Asia/Chongqing'));
```

**Comment by rogierschouten** [comment]
Hi @xlegs, which version of timezonecomplete are you using? The 'No offset found' message does not occur in TzDatabase.dstOffsetForRule method anymore.  By the way I did find it in the TzDatabase.letterForRule method, and it will be removed in the upcoming release 2.0.0

**Comment by xlegs** [comment]
v1.27.2

**Comment by xlegs** [comment]
I updated my version and it works. Thanks.
