### ISSUE TITLE
TypeError: Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by mgroenhoff** [SpiritIT/timezonecomplete#32]
This piece of code
```
new tz.DateTime(null).format("y");
```
Produced the following error
```
TypeError: Cannot read property 'clone' of undefined
    at convertFromUtc (C:\Source\eXLent_master\exlent\node_modules\timezonecomplete\dist\lib\datetime.js:56:23)
    at DateTime.get [as zoneDate] (C:\Source\eXLent_master\exlent\node_modules\timezonecomplete\dist\lib\datetime.js:199:34)
    at DateTime.format (C:\Source\eXLent_master\exlent\node_modules\timezonecomplete\dist\lib\datetime.js:851:34)
```

**Comment by rogierschouten** [comment]
fixed in v5.4.4:  more assertions added to DateTime constructor.
